# Generated by Django 4.2 on 2023-05-24 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='actualfilms',
            options={'verbose_name': 'Актуальный фильм', 'verbose_name_plural': 'Актуальный фильмы'},
        ),
        migrations.AlterModelOptions(
            name='places',
            options={'verbose_name': 'Место', 'verbose_name_plural': 'Места'},
        ),
        migrations.AlterModelOptions(
            name='rent',
            options={'verbose_name': 'Бронь', 'verbose_name_plural': 'Бронь'},
        ),
        migrations.AlterModelOptions(
            name='session',
            options={'verbose_name': 'Сеанс', 'verbose_name_plural': 'Сеансы'},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'Пользователь', 'verbose_name_plural': 'Пользователи'},
        ),
        migrations.AlterField(
            model_name='actualfilms',
            name='duration',
            field=models.TimeField(verbose_name='Длительность'),
        ),
        migrations.AlterField(
            model_name='actualfilms',
            name='poster',
            field=models.ImageField(upload_to='posters/%Y/%m/%d', verbose_name='Постер фильма'),
        ),
    ]
