# Generated by Django 4.2 on 2023-06-05 08:45

import booking.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0002_alter_actualfilms_options_alter_places_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='places',
            name='p1',
            field=models.IntegerField(default=1, validators=[booking.models.place_validator], verbose_name='Место 1'),
        ),
        migrations.AlterField(
            model_name='places',
            name='p10',
            field=models.IntegerField(default=1, validators=[booking.models.place_validator], verbose_name='Место 10'),
        ),
        migrations.AlterField(
            model_name='places',
            name='p11',
            field=models.IntegerField(default=1, validators=[booking.models.place_validator], verbose_name='Место 11'),
        ),
        migrations.AlterField(
            model_name='places',
            name='p12',
            field=models.IntegerField(default=1, validators=[booking.models.place_validator], verbose_name='Место 12'),
        ),
        migrations.AlterField(
            model_name='places',
            name='p13',
            field=models.IntegerField(default=1, validators=[booking.models.place_validator], verbose_name='Место 13'),
        ),
        migrations.AlterField(
            model_name='places',
            name='p14',
            field=models.IntegerField(default=1, validators=[booking.models.place_validator], verbose_name='Место 14'),
        ),
        migrations.AlterField(
            model_name='places',
            name='p15',
            field=models.IntegerField(default=1, validators=[booking.models.place_validator], verbose_name='Место 15'),
        ),
        migrations.AlterField(
            model_name='places',
            name='p16',
            field=models.IntegerField(default=1, validators=[booking.models.place_validator], verbose_name='Место 16'),
        ),
        migrations.AlterField(
            model_name='places',
            name='p17',
            field=models.IntegerField(default=1, validators=[booking.models.place_validator], verbose_name='Место 17'),
        ),
        migrations.AlterField(
            model_name='places',
            name='p18',
            field=models.IntegerField(default=1, validators=[booking.models.place_validator], verbose_name='Место 18'),
        ),
        migrations.AlterField(
            model_name='places',
            name='p19',
            field=models.IntegerField(default=1, validators=[booking.models.place_validator], verbose_name='Место 19'),
        ),
        migrations.AlterField(
            model_name='places',
            name='p2',
            field=models.IntegerField(default=1, validators=[booking.models.place_validator], verbose_name='Место 2'),
        ),
        migrations.AlterField(
            model_name='places',
            name='p20',
            field=models.IntegerField(default=1, validators=[booking.models.place_validator], verbose_name='Место 20'),
        ),
        migrations.AlterField(
            model_name='places',
            name='p21',
            field=models.IntegerField(default=1, validators=[booking.models.place_validator], verbose_name='Место 21'),
        ),
        migrations.AlterField(
            model_name='places',
            name='p22',
            field=models.IntegerField(default=1, validators=[booking.models.place_validator], verbose_name='Место 22'),
        ),
        migrations.AlterField(
            model_name='places',
            name='p23',
            field=models.IntegerField(default=1, validators=[booking.models.place_validator], verbose_name='Место 23'),
        ),
        migrations.AlterField(
            model_name='places',
            name='p24',
            field=models.IntegerField(default=1, validators=[booking.models.place_validator], verbose_name='Место 24'),
        ),
        migrations.AlterField(
            model_name='places',
            name='p25',
            field=models.IntegerField(default=1, validators=[booking.models.place_validator], verbose_name='Место 25'),
        ),
        migrations.AlterField(
            model_name='places',
            name='p3',
            field=models.IntegerField(default=1, validators=[booking.models.place_validator], verbose_name='Место 3'),
        ),
        migrations.AlterField(
            model_name='places',
            name='p4',
            field=models.IntegerField(default=1, validators=[booking.models.place_validator], verbose_name='Место 4'),
        ),
        migrations.AlterField(
            model_name='places',
            name='p5',
            field=models.IntegerField(default=1, validators=[booking.models.place_validator], verbose_name='Место 5'),
        ),
        migrations.AlterField(
            model_name='places',
            name='p6',
            field=models.IntegerField(default=1, validators=[booking.models.place_validator], verbose_name='Место 6'),
        ),
        migrations.AlterField(
            model_name='places',
            name='p7',
            field=models.IntegerField(default=1, validators=[booking.models.place_validator], verbose_name='Место 7'),
        ),
        migrations.AlterField(
            model_name='places',
            name='p8',
            field=models.IntegerField(default=1, validators=[booking.models.place_validator], verbose_name='Место 8'),
        ),
        migrations.AlterField(
            model_name='places',
            name='p9',
            field=models.IntegerField(default=1, validators=[booking.models.place_validator], verbose_name='Место 9'),
        ),
    ]
